scopes = [
  "deps",
  "eso",     # External Secrets Operator
  "otel",    # Opentelmetry
  "prom",    # Prometheus
  "gate",    # Gateway API
  "istio",
  "loki",
  "grafana",
  "tempo",
  "signoz",
  "vault",
  "consul",
]

tag_prefix = "v"

[commit_types]
fix = { changelog_title = "Bug Fixes" }
feat = { changelog_title = "Features" }
docs = { changelog_title = "Documentation" }
chore = { changelog_title = "Miscellaneous" }
refactor = { changelog_title = "Refactor" }
revert = { changelog_title = "Revert" }
perf = { changelog_title = "Performance" }
test = { changelog_title = "Testing" }
ci = { changelog_title = "CI/CD" }
# disabled types
build = {}
style = {}
