apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repo-istio.yaml
  - hr-istio-base.yaml
  - hr-istio-cni.yaml
  - hr-istio-ztunnel.yaml
  - hr-istiod.yaml
  - hr-istio-ingressgateway.yaml

# add one line of comment
