apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespaces/monitoring.yaml
  - ../../base/prometheus
  - ../../base/grafana
patches:
  - path: hr-grafana-values.yaml
    target:
      kind: HelmRelease
      name: grafana
