apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespaces/monitoring.yaml
  # - ../../base/opentelemetry
  - ../../base/prometheus
  - ../../base/tempo
  - ../../base/loki
  # - ../../base/grafana
# patches:
#   - path: hr-grafana-values.yaml
#     target:
#       kind: HelmRelease
#   - path: hr-opentelemetry-collector-values.yaml
#     target:
#       kind: HelmRelease
