name: E2E grafana-prometheus

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/e2e-grafana-prometheus.yml
      - base/prometheus/**
      - base/grafana/**
      - overlays/grafana-prometheus/**
      - namespaces/**
  push:
    branches: ["main"]

jobs:
  flux-e2e-test:
    runs-on: ubuntu-latest
    name: flux end-to-end test
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v5
      - name: Prepare for flux end-to-end test
        uses: ./.github/actions/pre-e2e-test
        with:
          password: ${{ secrets.GITHUB_TOKEN }}

      # ----- below are unique to "grafana-prometheus" ----- #
      - name: Setup cluster reconciliation
        run: |
          flux create kustomization grafana-prometheus \
            --source="GitRepository/$REPO_NAME" \
            --path="./overlays/grafana-prometheus"
      - name: Verify cluster reconciliation
        run: |
          kubectl -n flux-system wait gitrepo/"$REPO_NAME" --for=condition=ready --timeout=30s
      - name: Verify helm reconciliation
        run: |
          kubectl -n flux-system wait ks/grafana-prometheus --for=condition=ready --timeout=30s
          kubectl -n flux-system wait helmrepo/prometheus --for=condition=ready --timeout=30s
          kubectl -n flux-system wait helmrepo/grafana --for=condition=ready --timeout=30s
          kubectl -n monitoring wait hr/prometheus --for=condition=ready --timeout=2m
          kubectl -n monitoring wait hr/grafana --for=condition=ready --timeout=2m
      - name: List deployed resources in tree
        run: |
          flux tree ks grafana-prometheus
      # ----- above are unique to "grafana-prometheus" ----- #

      - name: List all flux resources
        run: flux get all --all-namespaces
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
