name: E2E istio-ambient

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

jobs:
  flux-e2e-test:
    runs-on: ubuntu-latest
    name: flux end-to-end test
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v5
      - name: Prepare for flux end-to-end test
        uses: ./.github/actions/pre-e2e-test
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup cluster reconciliation
        run: |
          flux create kustomization istio-ambient \
            --source="GitRepository/$REPO_NAME" \
            --path="./overlays/istio-ambient"
      - name: Verify cluster reconciliation
        run: |
          kubectl -n flux-system wait gitrepo/"$REPO_NAME" --for=condition=ready --timeout=30s
      - name: Verify helm reconciliation
        run: |
          kubectl -n flux-system wait ks/istio-ambient --for=condition=ready --timeout=30s
          kubectl -n flux-system wait helmrepo/istio --for=condition=ready --timeout=30s
          kubectl -n istio-system wait hr/istio-base --for=condition=ready --timeout=30s
      - name: List deployed resources in tree
        run: |
          flux tree ks istio-ambient
      - name: Post processes for flux end-to-end test
        uses: ./.github/actions/post-e2e-test
