name: E2E otel-lgtm

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/e2e-otel-lgtm.yml
      - base/prometheus/**
      - base/grafana/**
      - base/tempo/**
      - base/loki/**
      - overlays/otel-lgtm/**
      - namespaces/**
  push:
    branches: ["main"]

jobs:
  flux-e2e-test:
    runs-on: ubuntu-latest
    name: flux end-to-end test
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v5
      - name: Prepare for flux end-to-end test
        uses: ./.github/actions/pre-e2e-test
        with:
          password: ${{ secrets.GITHUB_TOKEN }}

      # ----- below are unique to "otel-lgtm" ----- #
      - name: Setup cluster reconciliation
        run: |
          flux create kustomization otel-lgtm \
            --source="GitRepository/$REPO_NAME" \
            --path="./overlays/otel-lgtm"
      - name: Verify cluster reconciliation
        run: |
          kubectl -n flux-system wait gitrepo/"$REPO_NAME" --for=condition=ready --timeout=30s
      - name: Verify helm reconciliation
        run: |
          # ks (Kustomization)
          kubectl -n flux-system wait ks/otel-lgtm --for=condition=ready --timeout=30s
          # helmrepo (HelmRepository)
          kubectl -n flux-system wait helmrepo/opentelemetry --for=condition=ready --timeout=30s
          kubectl -n flux-system wait helmrepo/prometheus --for=condition=ready --timeout=30s
          kubectl -n flux-system wait helmrepo/grafana --for=condition=ready --timeout=30s
          kubectl -n flux-system wait helmrepo/tempo --for=condition=ready --timeout=30s
          kubectl -n flux-system wait helmrepo/loki --for=condition=ready --timeout=30s
          # hr (HelmRelease)
          kubectl -n monitoring wait hr/opentelemetry-collector --for=condition=ready --timeout=1m
          kubectl -n monitoring wait hr/prometheus --for=condition=ready --timeout=1m
          kubectl -n monitoring wait hr/grafana --for=condition=ready --timeout=1m
          kubectl -n monitoring wait hr/tempo --for=condition=ready --timeout=1m
          kubectl -n monitoring wait hr/loki --for=condition=ready --timeout=1m
      - name: List deployed resources in tree
        run: |
          flux tree ks otel-lgtm
      # ----- above are unique to "otel-lgtm" ----- #

      - name: List all flux resources
        run: flux get all --all-namespaces
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
