name: E2E Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

jobs:
  flux-deployment-test:
    runs-on: ubuntu-latest
    name: deploy in kubernetes by flux
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes in Docker
        uses: helm/kind-action@v1
        with:
          cluster_name: chart-testing-flux
      - name: Install Flux in Kubernetes Kind
        run: flux install --components-extra source-watcher
      - name: Setup cluster reconciliation
        run: |
          flux create source git "${REPO_NAME}" \
            --url="${{ github.event.repository.html_url }}" \
            --branch="${GITHUB_REF#refs/heads/}" \
            --username="${GITHUB_ACTOR}" \
            --password="${{ secrets.GITHUB_TOKEN }}" \
            --ignore-paths="clusters/**/flux-system/"
          flux create kustomization istio-ambient \
            --source="GitRepository/$REPO_NAME" \
            --path="./overlays/istio-ambient"
      - name: Verify cluster reconciliation
        run: |
          kubectl -n flux-system wait gitrepo/"$REPO_NAME" --for=condition=ready --timeout=30s
          kubectl -n flux-system wait ks/istio-ambient --for=condition=ready --timeout=30s
      - name: Verify helm reconciliation
        run: |
          kubectl -n flux-system wait helmrepo/istio --for=condition=ready --timeout=30s
          kubectl -n istio-system wait hr/istio-base --for=condition=ready --timeout=30s
      - name: List deployed resources in tree
        run: |
          flux tree ks istio-ambient
      - name: List all flux resources
        run: flux get all --all-namespaces
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
